# Generated by Django 3.2.17 on 2023-03-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0026_courseoverview_entrance_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCustomDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_key', models.TextField(null=True)),
                ('display_name', models.TextField(null=True)),
                ('Duration', models.IntegerField(default=60)),
                ('FocusArea', models.TextField(default='N/A')),
                ('Tags', models.TextField(blank=True, null=True)),
                ('course_type_choice', models.CharField(choices=[('Course', 'COURSE'), ('Assessment', 'ASSESSMENT'), ('Project', 'PROJECT'), ('Application', 'APPLICATION')], default='Course', max_length=50)),
                ('course_instructions', models.TextField(blank=True, null=True)),
                ('organization_logo_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Course Custom Details',
                'verbose_name_plural': 'Course Custom Details',
            },
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='Duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='FocusArea',
            field=models.TextField(default='C++'),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='is_Assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='Duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='FocusArea',
            field=models.TextField(default='C++'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='is_Assessment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courseoverview',
            name='course_custom_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_custom_details', to='course_overviews.coursecustomdetails'),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='course_custom_details',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='course_overviews.coursecustomdetails'),
        ),
    ]
