# Generated by Django 3.2.17 on 2023-03-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0054_alter_userregistration_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('learning_points', models.TextField(null=True)),
                ('program_overview', models.TextField(null=True)),
                ('program_instructions', models.TextField(null=True)),
                ('instructors', models.TextField(null=True)),
                ('program_schedule', models.TextField(null=True)),
                ('program_sessions', models.TextField(blank=True, null=True)),
                ('program_pace', models.CharField(choices=[('Self', 'SELF'), ('Instructor', 'INSTRUCTOR')], default='Instructor', max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('weekly_duration', models.CharField(max_length=100, null=True)),
                ('image_url', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=0)),
                ('focus_area', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100, null=True)),
                ('entity_group_type', models.CharField(choices=[('Program', 'PROGRAM'), ('Project', 'PROJECT')], default='Program', max_length=50)),
                ('support', models.TextField(null=True)),
                ('created_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization_logo_url', models.TextField(blank=True, null=True)),
                ('identifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programlist_identifier', to='student.courseidentifier')),
            ],
            options={
                'verbose_name': 'Entity Group',
                'db_table': 'entitygroup_entitygroup',
            },
        ),
        migrations.CreateModel(
            name='UserEntityGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('last_modified_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('entity_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprogram_user', to='user_programs.entitygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprogram_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User EntityGroup Mapping',
                'db_table': 'entitygroup_userentitygroupmapping',
            },
        ),
    ]
