# Generated by Django 3.2.17 on 2023-03-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0024_delete_proctoredexamstudentattempthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDEExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('container_command', models.CharField(blank=True, max_length=200, null=True)),
                ('server_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('is_embedded', models.BooleanField(default=True)),
                ('max_score', models.IntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('enable_git_oauth', models.BooleanField(default=False)),
                ('git_fork_repository', models.CharField(blank=True, max_length=100, null=True)),
                ('proctored_exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ideexam_exam', to='edx_proctoring.proctoredexam')),
            ],
            options={
                'verbose_name': 'IDE Exam',
                'db_table': 'ide_ideexam',
            },
        ),
        migrations.CreateModel(
            name='IDEExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_url', models.CharField(blank=True, max_length=200, null=True)),
                ('container_created_date', models.DateTimeField(blank=True, null=True)),
                ('container_port', models.CharField(blank=True, max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('git_detais', models.TextField(blank=True, null=True)),
                ('ide_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_attempt_exam', to='IDE_Exam.ideexams')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ide_attempt_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IDE Exam Attempt',
                'db_table': 'ide_ideexam_attempt',
            },
        ),
    ]
