# Generated by Django 3.2.17 on 2023-03-22 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0024_delete_proctoredexamstudentattempthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProctoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur_count', models.IntegerField(default=5)),
                ('blur_duration', models.IntegerField(default=120)),
                ('blur_restriction', models.BooleanField(default=True)),
                ('force_fullscreen', models.BooleanField(default=True)),
                ('disable_copy_paste', models.BooleanField(default=True)),
                ('enable_camera', models.BooleanField(default=True)),
                ('pop_up_window', models.BooleanField(default=True)),
                ('reason', models.TextField()),
                ('proctored_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproctoringconfiguration_exam', to='edx_proctoring.proctoredexam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproctoringconfiguration_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('status', models.TextField(null=True)),
                ('proctored_attempt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoringdata_exam', to='edx_proctoring.proctoredexamstudentattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoringdata_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'proctoring system data',
                'db_table': 'proctoringsystem_proctoringdata',
            },
        ),
        migrations.CreateModel(
            name='ProctoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur_count', models.IntegerField(default=5)),
                ('blur_duration', models.IntegerField(default=120)),
                ('blur_restriction', models.BooleanField(default=True)),
                ('force_fullscreen', models.BooleanField(default=True)),
                ('disable_copy_paste', models.BooleanField(default=True)),
                ('enable_camera', models.BooleanField(default=True)),
                ('pop_up_window', models.BooleanField(default=True)),
                ('proctored_exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proctoringconfiguration_exam', to='edx_proctoring.proctoredexam')),
            ],
        ),
    ]
