# Generated by Django 3.2.17 on 2023-03-20 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0045_auto_20230320_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 20, 8, 34, 16, 949022, tzinfo=utc)),
        ),
    ]
